# Use official OpenJDK 21 as base image
FROM eclipse-temurin:21-jdk-jammy

# Set working directory inside container
WORKDIR /app

# Copy Maven wrapper and pom.xml first for caching dependencies
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .

# Make Maven wrapper executable
RUN chmod +x mvnw

# Download dependencies only (caching layer)
RUN ./mvnw dependency:go-offline -B

# Copy the rest of the project
COPY src ./src

# Build the Spring Boot app (skip tests for faster build)
RUN ./mvnw clean package -DskipTests

# Expose the port the Spring Boot app runs on
EXPOSE 8080

# Set environment variables to be passed during runtime
ENV API_KEY=${API_KEY}
ENV API_URL=${API_URL}

# Run the app
ENTRYPOINT ["java","-jar","target/mailpilot-0.0.1-SNAPSHOT.jar"]
